name: gems
root: ~/PhD/gems
tmux_options: -2
windows:
  - main:
      layout: 10d3,160x58,0,0{79x58,0,0,0,80x58,80,0[80x28,80,0,2,80x29,80,29,3]}
      panes:
        - source .environment && git status && inv -l
        - source .environment && cd data && git status
        - cd experiment && source .environment && git status && inv -l
  - doc:
      layout: main-vertical
      panes:
        - cd docs && vim inherited-diversity.Rmd
        - cd docs
  - experiment:
      root: ~/PhD/gems/experiment
      layout: ecf7,160x58,0,0{79x58,0,0,2,80x58,80,0[80x45,80,0,6,80x12,80,46,7]}
      panes:
        - source .environment && git status && inv -l
        - source .environment && vim .
        - cd ~/Dropbox/LupyanExps/gems-experiment && git status
