---
output:
  bookdown::html_document2: {}
---

```{r config, include=FALSE}
library(knitr)
library(tidyverse)
opts_chunk$set(echo=FALSE)
```

```{r show-movements}
parse_pos <- function(position_strings) {
  positions <- stringr::str_split_fixed(position_strings, "-", n = 2) %>% as_data_frame()
  colnames(positions) <- c("x", "y")
  positions %>%
    mutate(x = as.numeric(x), y = as.numeric(y))
}

bind_positions <- function(results, position_column, prefix) {
  positions <- parse_pos(results[[position_column]])
  colnames(positions) <- paste(prefix, c("x", "y"), sep = "_")
  cbind(results, positions)
}

results <- read_csv("experiment/data/pierce.csv") %>%
  bind_positions("pos", "start") %>%
  bind_positions("selected", "end")

landscape_plot <- ggplot() +
  coord_equal(xlim = c(0, 99), ylim = c(0, 99)) +
  annotate("point", x = 50, y = 50, shape = 4)

landscape_plot %+% results +
  aes(start_x, start_y, xend = end_x, yend = end_y) +
  geom_segment(aes(group = quarry),
               arrow = arrow(length = unit(0.1,"cm")))

```