---
title: Pilot
output:
  html_document: {}
---
```{r config, include=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, cache=TRUE, fig.height=3)

library(tidyverse)
library(magrittr)

library(gems)
data("Pilot")

t_ <- list(
  theme = theme_minimal(),
  scale_color_instructions = 
    scale_color_brewer("Training", labels = c("Orientation", "Stripe width")),
  coord_landscape = coord_equal(xlim = c(0, 99), ylim = c(0, 99)),
  scale_x_orientation = scale_x_continuous("Orientation"),
  scale_y_spatial_frequency = scale_y_continuous("Spatial frequency")
)

label_training <- function(frame) {
  frame %>% mutate(training = ifelse(landscape_ix == 0, "training", "test"))
}

recode_training <- function(frame) {
  labels <- c("training", "test")
  map <- data_frame(
    training = labels,
    training_label = factor(labels, levels = labels)
  )
  if(missing(frame)) return(map)
  left_join(frame, map)
}

recode_landscape <- function(frame) {
  labels <- c("SimpleHill", "ReverseOrientation", "ReverseSpatialFrequency", "ReverseBoth")
  map <- data_frame(
    landscape_name = labels,
    landscape_label = factor(labels, levels = labels)
  )
  if(missing(frame)) return(map)
  left_join(frame, map)
}

Pilot %<>%
  label_training() %>%
  recode_training() %>%
  recode_landscape()
```

```{r fig.width=6}
ggplot(Pilot) +
  aes(trial, score) +
  geom_line(aes(group = interaction(subj_id, run, landscape_ix)),
            size = 0.1) +
  geom_line(stat = "summary", fun.y = "mean") +
  facet_wrap("training_label", scales = "free_x") +
  t_$theme
```

```{r, fig.width=6}
PilotTraining <- Pilot %>%
  filter(training == "training")

ggplot(PilotTraining) +
  aes(current_x, current_y, color = instructions, linetype = factor(run)) +
  geom_line(aes(group = interaction(subj_id, run))) +
  annotate("point", x = 5, y = 5, shape = 4) +
  annotate("point", x = 50, y = 50, shape = 4) +
  facet_wrap("subj_id") +
  t_$scale_x_orientation +
  t_$scale_y_spatial_frequency +
  t_$scale_color_instructions +
  t_$coord_landscape +
  t_$theme +
  theme(legend.position = "bottom")
```

```{r, fig.width=10}
PilotTest <- Pilot %>%
  filter(training == "test")

ggplot(PilotTest) +
  aes(current_x, current_y, color = instructions) +
  geom_line(aes(group = subj_id)) +
  annotate("point", x = 5, y = 5, shape = 4) +
  annotate("point", x = 50, y = 50, shape = 4) +
  facet_wrap("landscape_label", nrow = 1) +
  t_$scale_x_orientation +
  t_$scale_y_spatial_frequency +
  t_$scale_color_instructions +
  t_$coord_landscape +
  t_$theme +
  theme(legend.position = "bottom")
```